// ============================================================
//        ELITE TEMPLATES — SOCIAL MEDIA & E-COMMERCE
// ============================================================

import 'package:flutter/material.dart';
import 'template_models.dart';

// ============================================================
// 📱 SOCIAL MEDIA TEMPLATES
// ============================================================

const linkedInPostTemplate = AppTemplate(
  id: 'linkedin_post',
  name: 'LinkedIn Post',
  description: 'Professional posts that get engagement',
  tagline: 'Build your brand',
  category: TemplateCategory.social,
  icon: Icons.work,
  gradientColors: [Color(0xFF0A66C2), Color(0xFF004182)],
  isPro: false,
  estimatedMinutes: 2,
  defaultExport: ExportFormat.text,
  targetApp: 'LinkedIn',
  availableExports: [ExportFormat.text, ExportFormat.markdown],
  aiSystemPrompt: '''Write a LinkedIn post that feels authentic and gets engagement. Use line breaks for readability. Start with a hook. Include a personal take. End with a question or call to action. No cringe, no obvious AI vibes.''',
  sections: [
    TemplateSection(
      id: 'topic',
      title: 'What\'s Your Point?',
      hint: 'The insight, lesson, or story you want to share',
      aiPrompt: 'Build post around this core message.',
      icon: Icons.lightbulb,
      placeholder: 'Just learned that most startups fail not from bad ideas but from founder burnout, we need to talk about sustainable pace',
    ),
    TemplateSection(
      id: 'story',
      title: 'The Story/Context',
      hint: 'What happened? What did you observe? Personal experience?',
      aiPrompt: 'Use this as the narrative hook.',
      icon: Icons.auto_stories,
      required: false,
      placeholder: 'My cofounder and I almost burned out last year, working 80 hour weeks, thought it was necessary, it wasn\'t',
    ),
    TemplateSection(
      id: 'takeaway',
      title: 'The Takeaway',
      hint: 'What should people learn or do differently?',
      aiPrompt: 'Distill into actionable insight.',
      icon: Icons.psychology,
      placeholder: 'Now we work 50 hours max, company is growing faster, we\'re happier, quality over quantity',
    ),
  ],
);

const instagramCaptionTemplate = AppTemplate(
  id: 'instagram_caption',
  name: 'Instagram Caption',
  description: 'Captions that get likes and comments',
  tagline: 'Hook your followers',
  category: TemplateCategory.social,
  icon: Icons.camera_alt,
  gradientColors: [Color(0xFFE4405F), Color(0xFFBD1E59)],
  isPro: false,
  estimatedMinutes: 1,
  defaultExport: ExportFormat.text,
  targetApp: 'Instagram',
  availableExports: [ExportFormat.text],
  aiSystemPrompt: '''Write an Instagram caption that\'s engaging and authentic. Strong first line (it\'s what shows before "more"). Include relevant hashtags. Add a call to action or question. Match the vibe of the content described.''',
  sections: [
    TemplateSection(
      id: 'content',
      title: 'What\'s the Post?',
      hint: 'Describe the photo or video. What\'s the vibe?',
      aiPrompt: 'Match caption energy to content described.',
      icon: Icons.image,
      placeholder: 'Sunset photo from my trip to Bali, at this amazing beach club, feeling grateful and relaxed',
    ),
    TemplateSection(
      id: 'message',
      title: 'What Do You Want to Say?',
      hint: 'The feeling, message, or story behind it',
      aiPrompt: 'Incorporate personal message authentically.',
      icon: Icons.chat,
      required: false,
      placeholder: 'Finally taking time for myself after a crazy year, learning that rest is productive too',
    ),
    TemplateSection(
      id: 'cta',
      title: 'Call to Action',
      hint: 'What do you want followers to do? Comment? Visit? Tag someone?',
      aiPrompt: 'Include engaging call to action.',
      icon: Icons.touch_app,
      required: false,
      placeholder: 'Want people to share their favorite travel spots in comments',
    ),
  ],
);

const twitterThreadTemplate = AppTemplate(
  id: 'twitter_thread',
  name: 'Twitter/X Thread',
  description: 'Turn ideas into viral threads',
  tagline: 'Thread your thoughts',
  category: TemplateCategory.social,
  icon: Icons.tag,
  gradientColors: [Color(0xFF1DA1F2), Color(0xFF0C7ABF)],
  isPro: false,
  estimatedMinutes: 2,
  defaultExport: ExportFormat.text,
  targetApp: 'Twitter / X',
  availableExports: [ExportFormat.text, ExportFormat.markdown],
  aiSystemPrompt: '''Create a Twitter thread. First tweet must hook. Each tweet must stand alone but flow together. Number them. Keep under 280 characters each. End with summary or CTA. Make it shareable.''',
  sections: [
    TemplateSection(
      id: 'topic',
      title: 'Thread Topic',
      hint: 'What are you threading about? The main insight or story.',
      aiPrompt: 'Build thread around this core topic.',
      icon: Icons.lightbulb,
      placeholder: 'How I grew my newsletter from 0 to 10K subscribers in 6 months without paid ads',
    ),
    TemplateSection(
      id: 'points',
      title: 'Key Points',
      hint: 'The main points, tips, or story beats you want to cover',
      aiPrompt: 'Turn each point into a compelling tweet.',
      icon: Icons.list,
      placeholder: 'Started by writing daily, focused on one niche, engaged with bigger accounts, used lead magnets, consistency was key',
    ),
    TemplateSection(
      id: 'hook',
      title: 'The Hook',
      hint: 'What makes someone stop scrolling? The first line.',
      aiPrompt: 'Create scroll-stopping first tweet.',
      icon: Icons.flash_on,
      required: false,
      placeholder: 'Something bold like: 99% of newsletters fail because they ignore this one thing',
    ),
  ],
);

const youtubeDescriptionTemplate = AppTemplate(
  id: 'youtube_description',
  name: 'YouTube Description',
  description: 'SEO-optimized descriptions with timestamps',
  tagline: 'Get discovered',
  category: TemplateCategory.social,
  icon: Icons.play_circle,
  gradientColors: [Color(0xFFFF0000), Color(0xFFCC0000)],
  isPro: false,
  estimatedMinutes: 2,
  defaultExport: ExportFormat.text,
  targetApp: 'YouTube',
  availableExports: [ExportFormat.text, ExportFormat.markdown],
  aiSystemPrompt: '''Create a YouTube description optimized for search. Include: compelling summary, timestamps/chapters, relevant links placeholder, hashtags. Front-load keywords naturally.''',
  sections: [
    TemplateSection(
      id: 'video',
      title: 'Video Content',
      hint: 'What\'s the video about? Main topics covered?',
      aiPrompt: 'Create SEO-rich description paragraph.',
      icon: Icons.videocam,
      placeholder: 'Tutorial on how to build a React app from scratch, covering setup, components, state management, API calls, deployment',
    ),
    TemplateSection(
      id: 'chapters',
      title: 'Timestamps/Sections',
      hint: 'Main sections of the video with rough times if known',
      aiPrompt: 'Format as YouTube chapters.',
      icon: Icons.access_time,
      placeholder: 'Intro, setup around 2 min, components at 10 min, state at 20 min, API at 30 min, deployment at 45 min, conclusion',
    ),
    TemplateSection(
      id: 'keywords',
      title: 'Keywords',
      hint: 'What should this rank for? What would people search?',
      aiPrompt: 'Incorporate keywords naturally and as hashtags.',
      icon: Icons.tag,
      required: false,
      placeholder: 'React tutorial, React for beginners, how to build React app, learn React 2024',
    ),
  ],
);

const tiktokCaptionTemplate = AppTemplate(
  id: 'tiktok_caption',
  name: 'TikTok Caption',
  description: 'Captions + hashtags that trend',
  tagline: 'Go viral',
  category: TemplateCategory.social,
  icon: Icons.music_note,
  gradientColors: [Color(0xFF00F2EA), Color(0xFFFF0050)],
  isPro: false,
  estimatedMinutes: 1,
  defaultExport: ExportFormat.text,
  targetApp: 'TikTok',
  availableExports: [ExportFormat.text],
  aiSystemPrompt: '''Write a TikTok caption that\'s catchy and uses trending formats. Keep it short and punchy. Include relevant hashtags (mix of trending and niche). Use Gen-Z friendly tone if appropriate.''',
  sections: [
    TemplateSection(
      id: 'content',
      title: 'Video Content',
      hint: 'What\'s the TikTok about? What type of video?',
      aiPrompt: 'Match caption style to content type.',
      icon: Icons.videocam,
      placeholder: 'Day in my life as a software engineer, showing morning routine, work from home, coding, gym after',
    ),
    TemplateSection(
      id: 'vibe',
      title: 'Vibe/Tone',
      hint: 'Funny? Relatable? Educational? Inspirational?',
      aiPrompt: 'Match tone to specified vibe.',
      icon: Icons.mood,
      required: false,
      placeholder: 'Relatable, showing the chill parts of tech life, a bit self-deprecating',
    ),
  ],
);

// ============================================================
// 🛒 E-COMMERCE TEMPLATES
// ============================================================

const productListingTemplate = AppTemplate(
  id: 'product_listing',
  name: 'Product Listing',
  description: 'SEO-optimized listings for Amazon, Shopify, Etsy',
  tagline: 'Sell more',
  category: TemplateCategory.ecommerce,
  icon: Icons.shopping_bag,
  gradientColors: [Color(0xFFFF9900), Color(0xFFFF6600)],
  isPro: false,
  estimatedMinutes: 2,
  defaultExport: ExportFormat.text,
  targetApp: 'Amazon / Shopify / Etsy',
  availableExports: [ExportFormat.text, ExportFormat.csv, ExportFormat.html],
  aiSystemPrompt: '''Create a product listing optimized for search and conversion. Include: SEO title, bullet points with benefits, compelling description, relevant keywords. Focus on benefits over features.''',
  sections: [
    TemplateSection(
      id: 'product',
      title: 'Product Details',
      hint: 'What is it? Features, specs, materials, sizes',
      aiPrompt: 'Extract all product specifications.',
      icon: Icons.inventory_2,
      placeholder: 'Wireless bluetooth earbuds, 30 hour battery, noise canceling, sweat proof, comes with 3 ear tip sizes, charging case included',
    ),
    TemplateSection(
      id: 'benefits',
      title: 'Benefits',
      hint: 'Why would someone buy this? What problem does it solve?',
      aiPrompt: 'Transform features into customer benefits.',
      icon: Icons.star,
      placeholder: 'Great for gym, commute, work calls, never worry about battery dying, blocks out distractions',
    ),
    TemplateSection(
      id: 'audience',
      title: 'Target Customer',
      hint: 'Who buys this? What are they looking for?',
      aiPrompt: 'Tailor language to target audience.',
      icon: Icons.people,
      required: false,
      placeholder: 'Fitness enthusiasts, remote workers, commuters who want quality sound without high price',
    ),
    TemplateSection(
      id: 'keywords',
      title: 'Keywords',
      hint: 'What would people search to find this product?',
      aiPrompt: 'Incorporate keywords naturally throughout.',
      icon: Icons.search,
      required: false,
      placeholder: 'Wireless earbuds, bluetooth headphones, noise canceling earbuds, workout earbuds, best earbuds 2024',
    ),
  ],
);

const productReviewRequestTemplate = AppTemplate(
  id: 'review_request',
  name: 'Review Request Email',
  description: 'Get more product reviews',
  tagline: 'Build social proof',
  category: TemplateCategory.ecommerce,
  icon: Icons.rate_review,
  gradientColors: [Color(0xFF10B981), Color(0xFF059669)],
  isPro: true,
  estimatedMinutes: 2,
  defaultExport: ExportFormat.text,
  targetApp: 'Email / Klaviyo',
  availableExports: [ExportFormat.text, ExportFormat.html],
  aiSystemPrompt: '''Write a friendly, non-pushy review request email. Acknowledge their purchase, ask how they\'re enjoying it, make leaving a review easy. Include direct link placeholder.''',
  sections: [
    TemplateSection(
      id: 'product',
      title: 'Product Purchased',
      hint: 'What did they buy? When?',
      aiPrompt: 'Reference specific purchase.',
      icon: Icons.shopping_cart,
      placeholder: 'Bought our wireless earbuds 2 weeks ago',
    ),
    TemplateSection(
      id: 'tone',
      title: 'Brand Voice',
      hint: 'How does your brand speak? Formal? Casual? Fun?',
      aiPrompt: 'Match brand voice throughout.',
      icon: Icons.record_voice_over,
      placeholder: 'Friendly and casual, we\'re a small business, personal touch',
    ),
    TemplateSection(
      id: 'incentive',
      title: 'Incentive (Optional)',
      hint: 'Offering anything for a review? Discount? Entry to win?',
      aiPrompt: 'Include incentive naturally if provided.',
      icon: Icons.card_giftcard,
      required: false,
      placeholder: '10% off next purchase for leaving a review',
    ),
  ],
);

const salesEmailTemplate = AppTemplate(
  id: 'sales_email_sequence',
  name: 'Sales Email Sequence',
  description: 'Cold outreach that gets replies',
  tagline: 'Fill your pipeline',
  category: TemplateCategory.ecommerce,
  icon: Icons.email,
  gradientColors: [Color(0xFF3B82F6), Color(0xFF2563EB)],
  isPro: true,
  estimatedMinutes: 4,
  defaultExport: ExportFormat.text,
  availableExports: [ExportFormat.text, ExportFormat.markdown],
  aiSystemPrompt: '''Create a 3-email cold outreach sequence. Email 1: Value-first introduction. Email 2: Follow-up with social proof. Email 3: Breakup email. Short, personalized, not salesy. Focus on their pain, not your product.''',
  sections: [
    TemplateSection(
      id: 'target',
      title: 'Target Customer',
      hint: 'Who are you reaching out to? Industry, role, company size?',
      aiPrompt: 'Tailor messaging to this specific audience.',
      icon: Icons.person,
      placeholder: 'VP of Sales at mid-size SaaS companies, 50-200 employees, B2B',
    ),
    TemplateSection(
      id: 'pain',
      title: 'Their Pain Point',
      hint: 'What problem do they have that you solve?',
      aiPrompt: 'Lead with their pain in outreach.',
      icon: Icons.warning,
      placeholder: 'Sales teams wasting time on manual data entry, CRM is always outdated, losing deals from poor follow-up',
    ),
    TemplateSection(
      id: 'solution',
      title: 'Your Solution',
      hint: 'How do you solve it? Key benefit, not feature list.',
      aiPrompt: 'Present solution in terms of outcome.',
      icon: Icons.lightbulb,
      placeholder: 'Our tool auto-logs calls and emails, saves 5 hours per rep per week, CRM is always accurate',
    ),
    TemplateSection(
      id: 'proof',
      title: 'Social Proof',
      hint: 'Who else uses you? Results they got?',
      aiPrompt: 'Include in email 2 for credibility.',
      icon: Icons.verified,
      required: false,
      placeholder: 'Acme Corp increased close rate 30%, used by 500 sales teams, G2 leader',
    ),
  ],
);