// ============================================================
//        ELITE TEMPLATES — LEGAL & EMOTIONAL
// ============================================================

import 'package:flutter/material.dart';
import 'template_models.dart';

// ============================================================
// ⚖️ LEGAL & FINANCE TEMPLATES
// ============================================================

const insuranceAppealTemplate = AppTemplate(
  id: 'insurance_appeal',
  name: 'Insurance Claim Appeal',
  description: 'Fight denied claims and win',
  tagline: 'Get what you\'re owed',
  category: TemplateCategory.legal,
  icon: Icons.medical_services,
  gradientColors: [Color(0xFFEF4444), Color(0xFFDC2626)],
  isPro: true,
  estimatedMinutes: 6,
  defaultExport: ExportFormat.text,
  availableExports: [ExportFormat.text, ExportFormat.markdown],
  aiSystemPrompt: '''Write a formal insurance appeal letter. Be factual and firm. Reference policy terms. Include medical necessity language. Request specific action. Professional but assertive tone.''',
  sections: [
    TemplateSection(
      id: 'claim',
      title: 'Claim Details',
      hint: 'Claim number, date of service, what was denied, denial reason',
      aiPrompt: 'Document claim details for reference.',
      icon: Icons.description,
      placeholder: 'Claim 12345, MRI on Jan 15, denied as not medically necessary, need it to diagnose back pain',
    ),
    TemplateSection(
      id: 'medical',
      title: 'Medical Situation',
      hint: 'Your condition, symptoms, how long, what you\'ve tried',
      aiPrompt: 'Explain medical necessity clearly.',
      icon: Icons.medical_services,
      placeholder: 'Severe back pain for 6 months, tried physical therapy and medications, doctor says MRI needed to rule out disc issues',
    ),
    TemplateSection(
      id: 'doctor',
      title: 'Doctor\'s Position',
      hint: 'What does your doctor say? Why is this necessary?',
      aiPrompt: 'Include physician recommendation and reasoning.',
      icon: Icons.local_hospital,
      placeholder: 'Dr. Smith says MRI is essential, symptoms consistent with herniated disc, need imaging to plan treatment',
    ),
    TemplateSection(
      id: 'policy',
      title: 'Policy Coverage',
      hint: 'What does your policy say? Why should this be covered?',
      aiPrompt: 'Reference relevant policy language if known.',
      icon: Icons.policy,
      required: false,
      placeholder: 'Policy covers diagnostic imaging when medically necessary, this meets that criteria',
    ),
    TemplateSection(
      id: 'request',
      title: 'What You Want',
      hint: 'What are you asking for? Full coverage? Reconsideration?',
      aiPrompt: 'State requested action clearly.',
      icon: Icons.gavel,
      placeholder: 'Requesting full reversal of denial and coverage of MRI cost, expedited review due to ongoing pain',
    ),
  ],
);

const demandLetterTemplate = AppTemplate(
  id: 'demand_letter',
  name: 'Demand Letter',
  description: 'Professional legal demand that gets results',
  tagline: 'Get what you\'re owed',
  category: TemplateCategory.legal,
  icon: Icons.gavel,
  gradientColors: [Color(0xFF6366F1), Color(0xFF4F46E5)],
  isPro: true,
  estimatedMinutes: 5,
  defaultExport: ExportFormat.text,
  availableExports: [ExportFormat.text, ExportFormat.markdown],
  aiSystemPrompt: '''Write a firm, professional demand letter. State facts clearly. Reference any agreements or laws. Specify exact demand and deadline. Mention consequences of non-compliance. Formal legal tone but accessible language.''',
  sections: [
    TemplateSection(
      id: 'recipient',
      title: 'Who Are You Writing To',
      hint: 'Name, company, their role in the situation',
      aiPrompt: 'Address letter properly.',
      icon: Icons.person,
      placeholder: 'John\'s Property Management, my landlord, they manage my apartment at 123 Main St',
    ),
    TemplateSection(
      id: 'situation',
      title: 'What Happened',
      hint: 'Describe the issue. Dates, facts, what went wrong.',
      aiPrompt: 'Present facts chronologically and objectively.',
      icon: Icons.description,
      placeholder: 'Moved out March 1, left apartment clean, they kept my \$2000 deposit claiming damage that was there when I moved in',
    ),
    TemplateSection(
      id: 'evidence',
      title: 'Your Evidence',
      hint: 'What proves your case? Photos, receipts, witnesses, contracts?',
      aiPrompt: 'Reference supporting evidence.',
      icon: Icons.folder,
      placeholder: 'Have move-in photos showing existing damage, move-out walkthrough was approved, have email confirmation',
    ),
    TemplateSection(
      id: 'demand',
      title: 'What You Want',
      hint: 'Exact amount or action. Be specific.',
      aiPrompt: 'State demand clearly with specific amount or action.',
      icon: Icons.attach_money,
      placeholder: 'Return of full \$2000 deposit within 14 days',
    ),
    TemplateSection(
      id: 'consequence',
      title: 'Or Else',
      hint: 'What will you do if they don\'t comply? Small claims? Report?',
      aiPrompt: 'State consequences professionally.',
      icon: Icons.warning,
      required: false,
      placeholder: 'Will file in small claims court and report to tenant rights board if not resolved',
    ),
  ],
);

const realEstateOfferTemplate = AppTemplate(
  id: 'real_estate_offer',
  name: 'Real Estate Offer Letter',
  description: 'Win bidding wars with heart',
  tagline: 'Get your dream home',
  category: TemplateCategory.legal,
  icon: Icons.home,
  gradientColors: [Color(0xFF10B981), Color(0xFF059669)],
  isPro: false,
  estimatedMinutes: 4,
  defaultExport: ExportFormat.text,
  availableExports: [ExportFormat.text, ExportFormat.markdown],
  aiSystemPrompt: '''Write a warm, personal home offer letter. Connect emotionally with sellers. Share your story and why this home matters. Be genuine, not manipulative. Complement what they\'ve created.''',
  sections: [
    TemplateSection(
      id: 'intro',
      title: 'Introduce Yourself',
      hint: 'Who are you? Family situation? What do you do?',
      aiPrompt: 'Create warm personal introduction.',
      icon: Icons.people,
      placeholder: 'We\'re the Johnsons, married 5 years, I\'m a teacher, wife is a nurse, we have a 2 year old daughter',
    ),
    TemplateSection(
      id: 'love',
      title: 'Why You Love This Home',
      hint: 'What specifically drew you to it? Be specific about features.',
      aiPrompt: 'Express genuine appreciation for specific home features.',
      icon: Icons.favorite,
      placeholder: 'Fell in love with the backyard for our daughter to play, the kitchen is perfect for family dinners, love the neighborhood',
    ),
    TemplateSection(
      id: 'story',
      title: 'Your Story',
      hint: 'Why are you looking for a home? What does this mean to you?',
      aiPrompt: 'Share personal story authentically.',
      icon: Icons.auto_stories,
      placeholder: 'Been renting for 7 years, finally saved enough, want to give our daughter a real home to grow up in',
    ),
    TemplateSection(
      id: 'vision',
      title: 'Your Vision',
      hint: 'How do you see yourselves in this home? Future plans?',
      aiPrompt: 'Paint picture of life in the home.',
      icon: Icons.visibility,
      placeholder: 'See our daughter learning to ride bike in driveway, hosting Thanksgiving, maybe a dog someday',
    ),
    TemplateSection(
      id: 'respect',
      title: 'Honoring Their Home',
      hint: 'Acknowledge what they\'ve built. How will you care for it?',
      aiPrompt: 'Show respect for sellers\' attachment to home.',
      icon: Icons.handshake,
      required: false,
      placeholder: 'Can tell you\'ve loved this home, the garden is beautiful, we\'ll take great care of everything you\'ve created',
    ),
  ],
);

const freelanceProposalTemplate = AppTemplate(
  id: 'freelance_proposal',
  name: 'Freelance Proposal',
  description: 'Win more clients with killer proposals',
  tagline: 'Land the contract',
  category: TemplateCategory.legal,
  icon: Icons.handshake,
  gradientColors: [Color(0xFF8B5CF6), Color(0xFF7C3AED)],
  isPro: false,
  estimatedMinutes: 5,
  defaultExport: ExportFormat.text,
  availableExports: [ExportFormat.text, ExportFormat.markdown],
  aiSystemPrompt: '''Write a professional freelance proposal. Show you understand their problem. Present your solution clearly. Include timeline and pricing. Build confidence in your ability to deliver.''',
  sections: [
    TemplateSection(
      id: 'understanding',
      title: 'Their Problem',
      hint: 'What do they need? Restate their requirements to show understanding.',
      aiPrompt: 'Demonstrate clear understanding of client needs.',
      icon: Icons.psychology,
      placeholder: 'You need a new website that converts visitors to customers, current site is slow and outdated, launching new product in 2 months',
    ),
    TemplateSection(
      id: 'solution',
      title: 'Your Solution',
      hint: 'How will you solve it? What will you deliver?',
      aiPrompt: 'Present solution with clear deliverables.',
      icon: Icons.lightbulb,
      placeholder: 'Modern WordPress site with conversion-optimized landing page, mobile responsive, fast loading, product showcase section',
    ),
    TemplateSection(
      id: 'why_you',
      title: 'Why You',
      hint: 'Relevant experience, similar projects, what makes you right for this.',
      aiPrompt: 'Build credibility with relevant experience.',
      icon: Icons.verified,
      placeholder: 'Built 50+ WordPress sites, specialize in conversion optimization, increased client sales 40% on average, fast turnaround',
    ),
    TemplateSection(
      id: 'timeline',
      title: 'Timeline',
      hint: 'How long? Key milestones?',
      aiPrompt: 'Present realistic timeline with milestones.',
      icon: Icons.schedule,
      placeholder: 'Week 1 design mockups, week 2-3 development, week 4 testing, launch before your deadline',
    ),
    TemplateSection(
      id: 'pricing',
      title: 'Investment',
      hint: 'Your price, what\'s included, payment terms',
      aiPrompt: 'Present pricing clearly and confidently.',
      icon: Icons.attach_money,
      placeholder: '\$5000 total, includes design, development, 2 rounds revisions, 30 days support, 50% upfront',
    ),
  ],
);

// ============================================================
// 💕 EMOTIONAL TEMPLATES
// ============================================================

const weddingSpeechTemplate = AppTemplate(
  id: 'wedding_speech',
  name: 'Wedding Speech',
  description: 'Heartfelt speech that gets laughs and tears',
  tagline: 'Nail your moment',
  category: TemplateCategory.emotional,
  icon: Icons.celebration,
  gradientColors: [Color(0xFFEC4899), Color(0xFFBE185D)],
  isPro: false,
  estimatedMinutes: 5,
  defaultExport: ExportFormat.text,
  availableExports: [ExportFormat.text, ExportFormat.markdown],
  aiSystemPrompt: '''Write a heartfelt, balanced wedding speech. Mix humor with genuine emotion. Tell specific stories that reveal character. Keep it under 5 minutes. End with a memorable toast.''',
  sections: [
    TemplateSection(
      id: 'role',
      title: 'Your Role',
      hint: 'Best man? Maid of honor? Father? Your relationship to couple.',
      aiPrompt: 'Establish speaker role and relationship.',
      icon: Icons.person,
      placeholder: 'Best man, known the groom Jake for 20 years, grew up next door',
    ),
    TemplateSection(
      id: 'funny_story',
      title: 'Funny Memory',
      hint: 'A hilarious story that shows their personality. Keep it appropriate!',
      aiPrompt: 'Craft a funny story that reveals character without embarrassing.',
      icon: Icons.mood,
      placeholder: 'Time Jake tried to impress a girl by doing a backflip and landed in a bush, always trying too hard to impress',
    ),
    TemplateSection(
      id: 'change',
      title: 'How They Changed',
      hint: 'How did you see them change when they met their partner?',
      aiPrompt: 'Describe positive transformation after meeting partner.',
      icon: Icons.favorite,
      placeholder: 'When he met Sarah, suddenly he was calm, focused, happy in a way I\'d never seen, she brought out his best self',
    ),
    TemplateSection(
      id: 'couple_moment',
      title: 'A Moment That Shows Their Love',
      hint: 'A specific moment that captures what makes them special together.',
      aiPrompt: 'Tell a story that exemplifies their relationship.',
      icon: Icons.auto_awesome,
      placeholder: 'Saw Jake stay up all night caring for Sarah when she was sick, that\'s when I knew this was different',
    ),
    TemplateSection(
      id: 'partner',
      title: 'To the Partner',
      hint: 'What do you want to say directly to their partner?',
      aiPrompt: 'Address partner warmly, welcome to family.',
      icon: Icons.people,
      placeholder: 'Sarah, thank you for loving my best friend, welcome to our family, take care of each other',
    ),
    TemplateSection(
      id: 'toast',
      title: 'The Toast',
      hint: 'How do you want to end? What do you wish for them?',
      aiPrompt: 'Craft memorable closing toast.',
      icon: Icons.wine_bar,
      placeholder: 'To a lifetime of adventure, laughter, and love, to Jake and Sarah',
    ),
  ],
);

const eulogyTemplate = AppTemplate(
  id: 'eulogy',
  name: 'Eulogy',
  description: 'Honor someone\'s memory with dignity',
  tagline: 'A fitting tribute',
  category: TemplateCategory.emotional,
  icon: Icons.favorite_border,
  gradientColors: [Color(0xFF6366F1), Color(0xFF4F46E5)],
  isPro: false,
  estimatedMinutes: 8,
  defaultExport: ExportFormat.text,
  availableExports: [ExportFormat.text, ExportFormat.markdown],
  aiSystemPrompt: '''Write a dignified, heartfelt eulogy. Balance grief with celebration of life. Use specific stories and memories. Capture their essence for those who knew them and those who didn\'t. Offer comfort.''',
  sections: [
    TemplateSection(
      id: 'relationship',
      title: 'Your Relationship',
      hint: 'Who were they to you? How long did you know them?',
      aiPrompt: 'Establish your connection and right to speak.',
      icon: Icons.people,
      placeholder: 'My grandmother, Rose, 92 years old, knew her my whole life, lived next door growing up',
    ),
    TemplateSection(
      id: 'who',
      title: 'Who They Were',
      hint: 'How would you describe them to someone who never met them?',
      aiPrompt: 'Paint a picture of their personality and character.',
      icon: Icons.person,
      placeholder: 'Fiercest woman I knew, survived the war, raised 5 kids, always had cookies in the jar, sharp as a tack until the end',
    ),
    TemplateSection(
      id: 'story1',
      title: 'A Story That Shows Them',
      hint: 'A memory that captures who they really were.',
      aiPrompt: 'Tell a story that reveals their essential character.',
      icon: Icons.auto_stories,
      placeholder: 'At 85, she chased a burglar out of her house with a frying pan, told him he should be ashamed, made him apologize',
    ),
    TemplateSection(
      id: 'lessons',
      title: 'What They Taught You',
      hint: 'What did you learn from them? How did they shape you?',
      aiPrompt: 'Share lessons learned and impact on your life.',
      icon: Icons.school,
      placeholder: 'Taught me that strength isn\'t about being loud, it\'s about standing up quietly every single day, never complaining',
    ),
    TemplateSection(
      id: 'legacy',
      title: 'Their Legacy',
      hint: 'What will live on? How will they be remembered?',
      aiPrompt: 'Describe their lasting impact.',
      icon: Icons.star,
      placeholder: 'She lives on in her 12 grandkids, in her recipes, in the way we all learned to face hard things with grace',
    ),
    TemplateSection(
      id: 'close',
      title: 'Goodbye',
      hint: 'What do you want to say to them? Final words.',
      aiPrompt: 'Craft a gentle, meaningful farewell.',
      icon: Icons.favorite,
      placeholder: 'Rest now Grandma, you earned it, we\'ll carry you with us always, save me some cookies',
    ),
  ],
);

const weddingVowsTemplate = AppTemplate(
  id: 'wedding_vows',
  name: 'Wedding Vows',
  description: 'Personal vows from the heart',
  tagline: 'Your promises, your words',
  category: TemplateCategory.emotional,
  icon: Icons.favorite,
  gradientColors: [Color(0xFFF472B6), Color(0xFFEC4899)],
  isPro: true,
  estimatedMinutes: 5,
  defaultExport: ExportFormat.text,
  availableExports: [ExportFormat.text, ExportFormat.markdown],
  aiSystemPrompt: '''Write authentic, personal wedding vows. Sound like the speaker, not a greeting card. Include specific details about their partner and relationship. Balance humor and emotion. Make promises that are meaningful and keepable.''',
  sections: [
    TemplateSection(
      id: 'partner',
      title: 'About Your Partner',
      hint: 'Their name, what you love most about them, what makes them special.',
      aiPrompt: 'Capture what makes this person uniquely lovable.',
      icon: Icons.favorite,
      placeholder: 'Sarah, love how she laughs at her own jokes, how kind she is to strangers, her terrible taste in movies',
    ),
    TemplateSection(
      id: 'moment',
      title: 'A Moment You Knew',
      hint: 'When did you know they were the one? A specific moment.',
      aiPrompt: 'Describe the moment of realization.',
      icon: Icons.lightbulb,
      placeholder: 'Knew when I was sick for a week and she stayed by my side, never complained, just took care of me',
    ),
    TemplateSection(
      id: 'grateful',
      title: 'What They\'ve Given You',
      hint: 'How has loving them made you better?',
      aiPrompt: 'Express gratitude for their impact.',
      icon: Icons.auto_awesome,
      placeholder: 'Made me calmer, kinder, believe in myself more, showed me what real partnership looks like',
    ),
    TemplateSection(
      id: 'promises',
      title: 'Your Promises',
      hint: 'What do you promise them? Be specific and realistic.',
      aiPrompt: 'Create meaningful, specific promises.',
      icon: Icons.handshake,
      placeholder: 'Promise to make you coffee every morning, to always listen even when I\'m tired, to never stop dating you',
    ),
    TemplateSection(
      id: 'close',
      title: 'Your Commitment',
      hint: 'Final words to seal your vows.',
      aiPrompt: 'Close with powerful, simple commitment.',
      icon: Icons.favorite,
      placeholder: 'Choose you today and will choose you every day for the rest of my life',
    ),
  ],
);