// ============================================================
//        ELITE TEMPLATES — LIFE-CHANGING & PROFESSIONAL
// ============================================================

import 'package:flutter/material.dart';
import 'template_models.dart';

// ============================================================
// 🚀 LIFE-CHANGING TEMPLATES
// ============================================================

const resumeTemplate = AppTemplate(
  id: 'resume',
  name: 'Professional Resume',
  description: 'ATS-optimized resume that gets interviews',
  tagline: 'Land your dream job',
  category: TemplateCategory.lifeChanging,
  icon: Icons.description,
  gradientColors: [Color(0xFF8B5CF6), Color(0xFF6366F1)],
  isPro: false,
  estimatedMinutes: 5,
  defaultExport: ExportFormat.text,
  availableExports: [ExportFormat.text, ExportFormat.markdown, ExportFormat.html],
  aiSystemPrompt: '''Create a professional, ATS-optimized resume. Use strong action verbs, quantify achievements where possible, and ensure clean formatting. No fluff, no buzzwords without substance. Make every word count.''',
  sections: [
    TemplateSection(
      id: 'contact',
      title: 'Contact Info',
      hint: 'Your name, email, phone, city, LinkedIn',
      aiPrompt: 'Format as clean contact header',
      icon: Icons.person,
      placeholder: 'John Smith, john@email.com, 555-1234, San Francisco, linkedin.com/in/johnsmith',
    ),
    TemplateSection(
      id: 'summary',
      title: 'Professional Summary',
      hint: 'Your role, years of experience, key strengths, what you bring',
      aiPrompt: 'Create a compelling 2-3 sentence professional summary. No "I" statements. Strong and confident.',
      icon: Icons.auto_awesome,
      placeholder: 'Senior software engineer, 8 years experience, full-stack, led teams of 10, passionate about scalable systems',
    ),
    TemplateSection(
      id: 'experience',
      title: 'Work Experience',
      hint: 'For each job: company, title, dates, what you did, achievements with numbers',
      aiPrompt: 'Format each role with bullet points. Start bullets with action verbs. Include metrics and achievements. Most recent first.',
      icon: Icons.work,
      placeholder: 'Google, Senior Engineer, 2020-2024, built recommendation system that increased engagement 40%, led team of 5',
    ),
    TemplateSection(
      id: 'skills',
      title: 'Skills',
      hint: 'Technical skills, tools, languages, soft skills',
      aiPrompt: 'Organize into categories. List most relevant first. Include proficiency levels if mentioned.',
      icon: Icons.psychology,
      placeholder: 'Python, JavaScript, React, AWS, team leadership, agile, SQL, machine learning',
    ),
    TemplateSection(
      id: 'education',
      title: 'Education',
      hint: 'Degree, school, graduation year, relevant coursework or honors',
      aiPrompt: 'Format education entries. Include GPA if above 3.5. Mention relevant honors.',
      icon: Icons.school,
      required: false,
      placeholder: 'BS Computer Science, Stanford, 2016, cum laude, AI concentration',
    ),
    TemplateSection(
      id: 'extras',
      title: 'Additional',
      hint: 'Certifications, projects, volunteer work, languages, interests',
      aiPrompt: 'Include only if relevant and impressive. Keep concise.',
      icon: Icons.star,
      required: false,
      placeholder: 'AWS Certified, open source contributor, fluent in Spanish, marathon runner',
    ),
  ],
);

const coverLetterTemplate = AppTemplate(
  id: 'cover_letter',
  name: 'Cover Letter',
  description: 'Compelling cover letter that gets read',
  tagline: 'Stand out from the stack',
  category: TemplateCategory.lifeChanging,
  icon: Icons.mail,
  gradientColors: [Color(0xFF3B82F6), Color(0xFF1D4ED8)],
  isPro: false,
  estimatedMinutes: 4,
  defaultExport: ExportFormat.text,
  availableExports: [ExportFormat.text, ExportFormat.markdown],
  aiSystemPrompt: '''Write a compelling, personalized cover letter. Show genuine interest in the company. Connect your experience to their needs. Be confident but not arrogant. Keep it to one page.''',
  sections: [
    TemplateSection(
      id: 'company',
      title: 'Company & Role',
      hint: 'Company name, position, what they do, why you\'re interested',
      aiPrompt: 'Use this to personalize the letter and show genuine interest.',
      icon: Icons.business,
      placeholder: 'Stripe, Senior Engineer, payments infrastructure, love their developer focus',
    ),
    TemplateSection(
      id: 'hook',
      title: 'Opening Hook',
      hint: 'Why you\'re excited, a connection to the company, or a bold statement',
      aiPrompt: 'Create an attention-grabbing opening that\'s not generic.',
      icon: Icons.flash_on,
      placeholder: 'Used Stripe since my first startup, their API changed how I think about payments',
    ),
    TemplateSection(
      id: 'value',
      title: 'Your Value',
      hint: 'Your relevant experience, achievements, what you bring to THIS role',
      aiPrompt: 'Connect their needs to your specific experience. Use concrete examples.',
      icon: Icons.trending_up,
      placeholder: 'Built payment systems processing \$10M monthly, reduced fraud 60%, led platform team',
    ),
    TemplateSection(
      id: 'fit',
      title: 'Why This Company',
      hint: 'What excites you about their mission, culture, product, or team',
      aiPrompt: 'Show you\'ve done research. Be specific about what attracts you.',
      icon: Icons.favorite,
      placeholder: 'Their economic infrastructure mission, remote culture, Patrick\'s blog posts on scaling',
    ),
    TemplateSection(
      id: 'close',
      title: 'Call to Action',
      hint: 'How you\'d like to continue the conversation',
      aiPrompt: 'Confident close with clear next step.',
      icon: Icons.send,
      required: false,
      placeholder: 'Would love to discuss how I can help scale the platform team',
    ),
  ],
);

const collegeEssayTemplate = AppTemplate(
  id: 'college_essay',
  name: 'College Application Essay',
  description: 'Personal essay that gets you admitted',
  tagline: 'Tell your story, win admission',
  category: TemplateCategory.lifeChanging,
  icon: Icons.school,
  gradientColors: [Color(0xFFEC4899), Color(0xFFBE185D)],
  isPro: true,
  estimatedMinutes: 8,
  defaultExport: ExportFormat.text,
  availableExports: [ExportFormat.text, ExportFormat.markdown],
  aiSystemPrompt: '''Write an authentic, compelling personal essay. Show don't tell. Use vivid details and specific moments. Let the student's unique voice shine through. Avoid clichés and generic statements. The essay should reveal character, growth, and genuine reflection.''',
  sections: [
    TemplateSection(
      id: 'prompt',
      title: 'Essay Prompt',
      hint: 'The exact prompt or question you\'re answering',
      aiPrompt: 'Use this to ensure the essay directly addresses what\'s asked.',
      icon: Icons.help,
      placeholder: 'Describe a challenge you faced and how it changed you',
    ),
    TemplateSection(
      id: 'moment',
      title: 'The Moment',
      hint: 'A specific scene, event, or experience. Where were you? What happened?',
      aiPrompt: 'Use this as the vivid opening scene. Include sensory details.',
      icon: Icons.camera,
      placeholder: 'Standing in the hospital waiting room at 3am, my mom in surgery, I was 15',
    ),
    TemplateSection(
      id: 'context',
      title: 'Background',
      hint: 'What led to this moment? What was your life like before?',
      aiPrompt: 'Provide necessary context without over-explaining.',
      icon: Icons.history,
      placeholder: 'Only child, mom raised me alone, she worked two jobs, I never saw her struggle until then',
    ),
    TemplateSection(
      id: 'challenge',
      title: 'The Challenge',
      hint: 'What was hard? What did you struggle with? Be honest and vulnerable.',
      aiPrompt: 'Show the real difficulty. Don\'t minimize or dramatize.',
      icon: Icons.warning,
      placeholder: 'Had to take care of her recovery, manage the house, keep my grades up, felt alone and scared',
    ),
    TemplateSection(
      id: 'growth',
      title: 'What You Learned',
      hint: 'How did this change you? What do you understand now that you didn\'t before?',
      aiPrompt: 'Show genuine reflection and maturity. Avoid clichés.',
      icon: Icons.lightbulb,
      placeholder: 'Learned I was stronger than I thought, that asking for help isn\'t weakness, that family is everything',
    ),
    TemplateSection(
      id: 'now',
      title: 'Who You Are Now',
      hint: 'How does this connect to who you are today and your future goals?',
      aiPrompt: 'Connect the experience to present identity and future aspirations.',
      icon: Icons.arrow_forward,
      placeholder: 'Now volunteer at hospital, want to study nursing, help other families going through hard times',
    ),
  ],
);

const pitchDeckTemplate = AppTemplate(
  id: 'pitch_deck',
  name: 'Investor Pitch',
  description: 'Compelling startup pitch that raises money',
  tagline: 'Get funded',
  category: TemplateCategory.lifeChanging,
  icon: Icons.rocket_launch,
  gradientColors: [Color(0xFF10B981), Color(0xFF059669)],
  isPro: true,
  estimatedMinutes: 10,
  defaultExport: ExportFormat.markdown,
  availableExports: [ExportFormat.text, ExportFormat.markdown, ExportFormat.html],
  aiSystemPrompt: '''Create a compelling investor pitch following the classic structure. Be concise and punchy. Lead with the problem, show massive market opportunity, explain why this team wins. Use concrete numbers. Every slide should make them want to see the next one.''',
  sections: [
    TemplateSection(
      id: 'hook',
      title: 'One-Liner',
      hint: 'Describe your company in one sentence. What do you do?',
      aiPrompt: 'Create a memorable one-liner that instantly communicates value.',
      icon: Icons.flash_on,
      placeholder: 'We\'re Uber for dog walking, on-demand pet care in 15 minutes',
    ),
    TemplateSection(
      id: 'problem',
      title: 'The Problem',
      hint: 'What painful problem exists? Who has it? How bad is it?',
      aiPrompt: 'Make the problem feel urgent and relatable. Use specific examples.',
      icon: Icons.error,
      placeholder: '65% of dog owners feel guilty leaving pets alone, existing services need 24hr notice, unreliable',
    ),
    TemplateSection(
      id: 'solution',
      title: 'Your Solution',
      hint: 'How do you solve it? What\'s your product? Why is it 10x better?',
      aiPrompt: 'Explain the solution clearly. Show the aha moment.',
      icon: Icons.lightbulb,
      placeholder: 'App connects you with vetted walkers in 15 min, GPS tracking, photo updates, subscription plans',
    ),
    TemplateSection(
      id: 'market',
      title: 'Market Size',
      hint: 'How big is the opportunity? TAM, SAM, SOM if you know them.',
      aiPrompt: 'Present market size compellingly. Use credible sources.',
      icon: Icons.pie_chart,
      placeholder: 'Pet care is \$100B market, dog services \$30B, urban on-demand segment \$5B and growing 20% yearly',
    ),
    TemplateSection(
      id: 'traction',
      title: 'Traction',
      hint: 'What have you achieved? Users, revenue, growth rate, key milestones.',
      aiPrompt: 'Lead with your best metrics. Show momentum and growth rate.',
      icon: Icons.trending_up,
      placeholder: '10K users, \$50K MRR, 30% month-over-month growth, launched 6 months ago, 4.9 star rating',
    ),
    TemplateSection(
      id: 'business',
      title: 'Business Model',
      hint: 'How do you make money? Unit economics if you have them.',
      aiPrompt: 'Explain revenue model clearly. Show path to profitability.',
      icon: Icons.attach_money,
      placeholder: '20% take rate on bookings, \$15 average order, \$3 CAC, \$200 LTV, subscription tier at \$29/mo',
    ),
    TemplateSection(
      id: 'team',
      title: 'Team',
      hint: 'Who are the founders? Why are you the ones to win?',
      aiPrompt: 'Highlight relevant experience and unfair advantages.',
      icon: Icons.people,
      placeholder: 'Ex-Uber operations lead, ex-Rover engineer, built and sold pet startup before, dog obsessed',
    ),
    TemplateSection(
      id: 'competition',
      title: 'Competition',
      hint: 'Who else is in the space? Why will you win?',
      aiPrompt: 'Acknowledge competition honestly. Show your differentiation.',
      icon: Icons.compare_arrows,
      required: false,
      placeholder: 'Rover is scheduled, not on-demand. Wag has quality issues. We\'re faster, more reliable, tech-first',
    ),
    TemplateSection(
      id: 'ask',
      title: 'The Ask',
      hint: 'How much are you raising? What will you use it for?',
      aiPrompt: 'Be specific about raise and use of funds. Show clear milestones.',
      icon: Icons.account_balance,
      placeholder: 'Raising \$2M seed, 18 months runway, expand to 5 cities, hit \$500K MRR, then Series A',
    ),
  ],
);

const immigrationLetterTemplate = AppTemplate(
  id: 'immigration_letter',
  name: 'Immigration Support Letter',
  description: 'Professional support letter for visa applications',
  tagline: 'Help someone stay',
  category: TemplateCategory.lifeChanging,
  icon: Icons.flight,
  gradientColors: [Color(0xFF0891B2), Color(0xFF0E7490)],
  isPro: true,
  estimatedMinutes: 6,
  defaultExport: ExportFormat.text,
  availableExports: [ExportFormat.text, ExportFormat.markdown],
  aiSystemPrompt: '''Write a formal, compelling immigration support letter. Be specific about the relationship and the applicant's character. Include concrete examples. Use professional language appropriate for government review. Be truthful and sincere.''',
  sections: [
    TemplateSection(
      id: 'writer',
      title: 'About You (Letter Writer)',
      hint: 'Your name, relationship to applicant, how long you\'ve known them',
      aiPrompt: 'Establish credibility as letter writer.',
      icon: Icons.person,
      placeholder: 'Sarah Johnson, employer for 3 years, direct supervisor at TechCorp',
    ),
    TemplateSection(
      id: 'applicant',
      title: 'About the Applicant',
      hint: 'Their name, what visa they\'re applying for, basic background',
      aiPrompt: 'Introduce the applicant professionally.',
      icon: Icons.badge,
      placeholder: 'Maria Chen, H1B extension, software engineer, been in US 5 years',
    ),
    TemplateSection(
      id: 'character',
      title: 'Character & Qualities',
      hint: 'What makes them a good person? Specific examples of their character.',
      aiPrompt: 'Provide specific examples that demonstrate positive character.',
      icon: Icons.star,
      placeholder: 'Exceptional work ethic, mentors junior engineers, organized company volunteer day, everyone respects her',
    ),
    TemplateSection(
      id: 'contributions',
      title: 'Contributions',
      hint: 'How have they contributed to work, community, or your life?',
      aiPrompt: 'Detail specific, measurable contributions.',
      icon: Icons.volunteer_activism,
      placeholder: 'Led project saving \$2M, teaches coding to underprivileged kids on weekends, key team member',
    ),
    TemplateSection(
      id: 'impact',
      title: 'Impact if Denied',
      hint: 'What would be lost if they had to leave?',
      aiPrompt: 'Explain the genuine impact thoughtfully.',
      icon: Icons.warning,
      required: false,
      placeholder: 'Critical to our AI team, no one else has her expertise, would set back project 2 years',
    ),
  ],
);

// ============================================================
// 💼 PROFESSIONAL TEMPLATES
// ============================================================

const meetingNotesTemplate = AppTemplate(
  id: 'meeting_notes',
  name: 'Meeting → Action Items',
  description: 'Turn any meeting into structured notes and tasks',
  tagline: 'Never lose a follow-up',
  category: TemplateCategory.professional,
  icon: Icons.groups,
  gradientColors: [Color(0xFF3B82F6), Color(0xFF2563EB)],
  isPro: false,
  estimatedMinutes: 2,
  defaultExport: ExportFormat.markdown,
  targetApp: 'Notion / Docs',
  availableExports: [ExportFormat.text, ExportFormat.markdown, ExportFormat.csv],
  aiSystemPrompt: '''Convert meeting voice dump into structured notes. Extract clear action items with owners and deadlines. Summarize key decisions. Be concise but complete.''',
  sections: [
    TemplateSection(
      id: 'context',
      title: 'Meeting Context',
      hint: 'What meeting? Who was there? Date?',
      aiPrompt: 'Create meeting header with attendees and date.',
      icon: Icons.info,
      placeholder: 'Weekly product sync, me, Sarah, Mike, John, today',
    ),
    TemplateSection(
      id: 'discussed',
      title: 'What Was Discussed',
      hint: 'Main topics, updates, issues raised',
      aiPrompt: 'Organize into clear topic sections with key points.',
      icon: Icons.chat,
      placeholder: 'Talked about Q3 roadmap, Sarah\'s team is behind on auth feature, Mike wants to change the homepage design',
    ),
    TemplateSection(
      id: 'decisions',
      title: 'Decisions Made',
      hint: 'What was decided? Any conclusions reached?',
      aiPrompt: 'List decisions clearly and definitively.',
      icon: Icons.check_circle,
      placeholder: 'Agreed to push auth to Q4, approved homepage redesign, will hire contractor for mobile',
    ),
    TemplateSection(
      id: 'actions',
      title: 'Action Items',
      hint: 'Who needs to do what? By when?',
      aiPrompt: 'Format as clear action items: [Owner] - [Task] - [Deadline]',
      icon: Icons.task_alt,
      placeholder: 'Sarah will send updated timeline by Friday, Mike will create design mockups next week, I\'ll interview contractors',
    ),
  ],
);

const salesCrmTemplate = AppTemplate(
  id: 'sales_crm',
  name: 'Sales Call → CRM',
  description: 'Log sales calls perfectly in seconds',
  tagline: 'Never forget a detail',
  category: TemplateCategory.professional,
  icon: Icons.phone_in_talk,
  gradientColors: [Color(0xFF10B981), Color(0xFF059669)],
  isPro: false,
  estimatedMinutes: 1,
  defaultExport: ExportFormat.text,
  targetApp: 'Salesforce / HubSpot',
  availableExports: [ExportFormat.text, ExportFormat.csv, ExportFormat.json],
  aiSystemPrompt: '''Format sales call notes for CRM entry. Extract: contact info, company details, pain points, next steps, deal value, and timeline. Be structured and factual.''',
  sections: [
    TemplateSection(
      id: 'contact',
      title: 'Contact & Company',
      hint: 'Who did you talk to? Company? Their role?',
      aiPrompt: 'Extract contact and company information.',
      icon: Icons.person,
      placeholder: 'John Smith, VP of Engineering at Acme Corp, about 500 employees',
    ),
    TemplateSection(
      id: 'situation',
      title: 'Their Situation',
      hint: 'What are they dealing with? Pain points? Current solution?',
      aiPrompt: 'Summarize prospect situation and pain points.',
      icon: Icons.psychology,
      placeholder: 'Struggling with slow deployments, using Jenkins, takes 2 hours per deploy, engineers frustrated',
    ),
    TemplateSection(
      id: 'interest',
      title: 'Interest Level',
      hint: 'How interested were they? Hot, warm, cold? Budget?',
      aiPrompt: 'Assess deal temperature and buying signals.',
      icon: Icons.thermostat,
      placeholder: 'Very interested, has budget approved, wants to decide this quarter, comparing us to 2 others',
    ),
    TemplateSection(
      id: 'next',
      title: 'Next Steps',
      hint: 'What happens next? When? Who needs to do what?',
      aiPrompt: 'List clear next steps with dates.',
      icon: Icons.arrow_forward,
      placeholder: 'Sending proposal tomorrow, demo with their team Thursday, decision by end of month',
    ),
  ],
);

const performanceReviewTemplate = AppTemplate(
  id: 'performance_review',
  name: 'Performance Review',
  description: 'Write thoughtful reviews in minutes',
  tagline: 'Fair, constructive feedback',
  category: TemplateCategory.professional,
  icon: Icons.assessment,
  gradientColors: [Color(0xFFF59E0B), Color(0xFFD97706)],
  isPro: true,
  estimatedMinutes: 5,
  defaultExport: ExportFormat.text,
  availableExports: [ExportFormat.text, ExportFormat.markdown],
  aiSystemPrompt: '''Write a balanced, constructive performance review. Be specific with examples. Acknowledge strengths genuinely. Frame growth areas constructively. End with clear development goals.''',
  sections: [
    TemplateSection(
      id: 'employee',
      title: 'Employee Info',
      hint: 'Name, role, review period, your relationship',
      aiPrompt: 'Create review header.',
      icon: Icons.person,
      placeholder: 'Alex Chen, Senior Engineer, Q1-Q4 2024, direct report for 2 years',
    ),
    TemplateSection(
      id: 'achievements',
      title: 'Key Achievements',
      hint: 'What did they accomplish? Big wins? Impact?',
      aiPrompt: 'Highlight achievements with specific metrics and impact.',
      icon: Icons.emoji_events,
      placeholder: 'Led the payment migration, zero downtime, saved \$200K yearly, mentored 2 juniors who got promoted',
    ),
    TemplateSection(
      id: 'strengths',
      title: 'Strengths',
      hint: 'What are they great at? What should they keep doing?',
      aiPrompt: 'Describe strengths with specific examples.',
      icon: Icons.star,
      placeholder: 'Excellent problem solver, great at breaking down complex problems, team loves working with him, very reliable',
    ),
    TemplateSection(
      id: 'growth',
      title: 'Areas for Growth',
      hint: 'Where can they improve? Be constructive and specific.',
      aiPrompt: 'Frame growth areas constructively with actionable suggestions.',
      icon: Icons.trending_up,
      placeholder: 'Could communicate more in meetings, sometimes takes on too much, needs to delegate more, documentation could improve',
    ),
    TemplateSection(
      id: 'goals',
      title: 'Goals for Next Period',
      hint: 'What should they focus on? Development areas?',
      aiPrompt: 'Set clear, measurable goals.',
      icon: Icons.flag,
      placeholder: 'Lead the new API project, present at one all-hands, mentor one new hire, take leadership training',
    ),
  ],
);

const clientIntakeTemplate = AppTemplate(
  id: 'client_intake',
  name: 'Client Intake',
  description: 'Capture new client details perfectly',
  tagline: 'Start relationships right',
  category: TemplateCategory.professional,
  icon: Icons.person_add,
  gradientColors: [Color(0xFF8B5CF6), Color(0xFF7C3AED)],
  isPro: false,
  estimatedMinutes: 3,
  defaultExport: ExportFormat.text,
  availableExports: [ExportFormat.text, ExportFormat.csv, ExportFormat.json],
  aiSystemPrompt: '''Create a comprehensive client intake summary. Organize information clearly for future reference. Highlight key requirements and any red flags.''',
  sections: [
    TemplateSection(
      id: 'client',
      title: 'Client Information',
      hint: 'Name, company, contact info, how they found you',
      aiPrompt: 'Format client contact information.',
      icon: Icons.person,
      placeholder: 'Jane Doe, Acme Consulting, jane@acme.com, referred by Mike Johnson',
    ),
    TemplateSection(
      id: 'needs',
      title: 'What They Need',
      hint: 'What are they looking for? What problem needs solving?',
      aiPrompt: 'Summarize client requirements clearly.',
      icon: Icons.help,
      placeholder: 'Needs complete website redesign, current site is 5 years old, wants modern look, mobile-first',
    ),
    TemplateSection(
      id: 'timeline',
      title: 'Timeline & Budget',
      hint: 'When do they need it? What\'s the budget?',
      aiPrompt: 'Note timeline and budget constraints.',
      icon: Icons.schedule,
      placeholder: 'Wants to launch by March, budget around \$15-20K, some flexibility if needed',
    ),
    TemplateSection(
      id: 'notes',
      title: 'Additional Notes',
      hint: 'Any other important details? Preferences? Red flags?',
      aiPrompt: 'Include any relevant additional information.',
      icon: Icons.note,
      required: false,
      placeholder: 'Very particular about fonts, had bad experience with last designer, prefers Slack communication',
    ),
  ],
);

const incidentReportTemplate = AppTemplate(
  id: 'incident_report',
  name: 'Incident Report',
  description: 'Document incidents accurately and fast',
  tagline: 'Capture every detail',
  category: TemplateCategory.professional,
  icon: Icons.report_problem,
  gradientColors: [Color(0xFFEF4444), Color(0xFFDC2626)],
  isPro: false,
  estimatedMinutes: 3,
  defaultExport: ExportFormat.text,
  availableExports: [ExportFormat.text, ExportFormat.markdown],
  aiSystemPrompt: '''Create a factual, objective incident report. Include precise times and details. Avoid speculation or blame. Focus on what happened, not why.''',
  sections: [
    TemplateSection(
      id: 'when',
      title: 'When & Where',
      hint: 'Date, time, location of incident',
      aiPrompt: 'Document time and location precisely.',
      icon: Icons.access_time,
      placeholder: 'Today at 2:30pm, warehouse section B, near loading dock 3',
    ),
    TemplateSection(
      id: 'what',
      title: 'What Happened',
      hint: 'Describe the incident objectively. What occurred?',
      aiPrompt: 'Describe incident factually without speculation.',
      icon: Icons.description,
      placeholder: 'Forklift backed into shelf, shelf tipped over, boxes fell, forklift driver jumped clear',
    ),
    TemplateSection(
      id: 'who',
      title: 'People Involved',
      hint: 'Who was involved? Any injuries? Witnesses?',
      aiPrompt: 'List all involved parties and witnesses.',
      icon: Icons.people,
      placeholder: 'Driver was Tom Smith, no injuries, witnessed by Sarah Johnson and Mike Chen',
    ),
    TemplateSection(
      id: 'response',
      title: 'Response & Actions',
      hint: 'What was done? First aid? Area secured?',
      aiPrompt: 'Document response actions taken.',
      icon: Icons.health_and_safety,
      placeholder: 'Area blocked off, supervisor notified, photos taken, driver sent for drug test per policy',
    ),
    TemplateSection(
      id: 'followup',
      title: 'Follow-up Needed',
      hint: 'What needs to happen next?',
      aiPrompt: 'List required follow-up actions.',
      icon: Icons.checklist,
      required: false,
      placeholder: 'Need to review camera footage, shelf needs inspection, retraining may be needed',
    ),
  ],
);
